---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test-dev
  namespace: dev-jpto-dev
  labels:
    app: web-test-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-test-dev
  template:
    metadata:
      labels:
        app: web-test-dev
    spec:
      containers:
      - name: web-test-dev
        image: ghcr.io/jpconstantineau/jpconstantineau-web-test:dev
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-test-dev-service
  namespace: dev-jpto-dev
spec:
  selector:
    app: web-test-dev
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-test-dev-ingress
  namespace: dev-jpto-dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: test.dev.jpto.dev
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: web-test-dev-service
            port: 
              number: 80
  tls:
  - hosts: 
    - test.dev.jpto.dev
    secretName: test.dev.jpto.dev-tls-production